[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "12.13.1"
  YARN_VERSION = "1.22.0"

[[redirects]]
  from = "https://janosh.netlify.com/*"
  to = "https://janosh.io/:splat"
  force = true
