[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "14.5.0"
  YARN_VERSION = "1.22.4"

[[redirects]]
  from = "https://janosh.netlify.com/*"
  to = "https://janosh.dev/:splat"
  force = true

[[redirects]]
  from = "https://janosh.io/*"
  to = "https://janosh.dev/:splat"
  force = true
